web:
  restart: always
  build: ./web
  expose:
  - "8000"
  links:
  #- postgres:postgres
  - postgis:postgis
  volumes:
  - /usr/src/app
  - /usr/src/app/static
  env_file: .env
  environment:
    DEBUG: 'true'
  command: /usr/local/bin/gunicorn master_thesis_backend.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
  - "80:80"
  volumes:
  - pgdata:/var/lib/postgresql/data/
  - pgisdata:/var/lib/postgis/data/
  volumes_from:
  - web
  links:
  - web:web

#postgres:
  #restart: always
  #image: postgres:latest
  #ports:
  #- "5432:5432"
  #volumes:
  #- pgdata:/var/lib/postgresql/data

postgis:
  restart: always
  image: kartoza/postgis:latest
  ports:
  - "5432:5432"
  #environment:
    #POSTGRES_USER: 'postgres'
    #POSTGRES_PASS: 'postgres'
    #POSTGRES_DBNAME: 'postgres'
  volumes:
  - pgisdata:/var/lib/postgis/data/
