version: "2.1"

services:
  web_base:
    build: 
      context: ./web
      dockerfile: DockerfileBase
    container_name: web_base
    image: web_base:latest
    volumes:
      - web_static:/usr/src/app/static

  web:
    restart: always
    build: ./web
    container_name: web
    depends_on:
      - web_base
    expose:
      - 8000
      - 535
    links:
      - postgis:postgis
      - redis:redis
    env_file: ${WEB_ENV_FILE}
    command: ./run_web.sh
    volumes:
      - web:/usr/src/app
      - web_static:/usr/src/app/static

  celery_worker:
    restart: always
    build: ./web
    container_name: celery_worker
    depends_on:
      - web_base
      - redis
    command: ./run_celery.sh
    env_file: ${WEB_ENV_FILE}
    links:
      - postgis:postgis
      - redis:redis
    volumes:
      - web:/usr/src/app
      - web_static:/usr/src/app/static

  letsencrypt-proxy:
    build: docker-nginx-letsencrypt-proxy
    ports:
      - 443:443
      - 80:80
    container_name: letsencrypt-proxy
    env_file: ${ENV_FILE}
    volumes:
      - letsencrypt:/etc/letsencrypt
      - /var/www/
    links:
      - nginx

  nginx:
    restart: always
    build: ./nginx/
    container_name: nginx
    volumes:
      - web_static:/usr/src/app/static
      - frontend:/usr/src/frontend
    links:
      - web:web

  postgis:
    restart: always
    build: ./postgis
    container_name: postgis
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/9.5/main
      - pgisdata:/var/lib/postgis/data/
    env_file: ${ENV_FILE}

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  frontend:
    #restart: always
    build: ./frontend
    container_name: frontend
    env_file: ${ENV_FILE}
    command: echo "Ok"
    volumes:
      - frontend:/usr/src/frontend

volumes:
  web:
  redisdata:
  pgisdata:
  pgdata:
  web_static:
  frontend:
  letsencrypt:
