version: '2'

services:
  web_base:
    build: ./web_base
    container_name: web_base
    image: web_base:latest

    volumes:
      - /usr/src/app
      - /usr/src/app/static

  web:
    restart: always
    build: ./web
    container_name: web
    depends_on:
      - web_base
    expose:
      - "8000"
    links:
      - postgis:postgis
      - redis:redis
    volumes:
      - /usr/src/app
      - /usr/src/app/static
    env_file: web/.env.develop
    environment:
      DEBUG: 'true'
      command: /usr/local/bin/gunicorn master_thesis_backend.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    container_name: nginx
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
    ports:
        - 443:443
        - 80:80

  postgis:
    restart: always
    image: kartoza/postgis:latest
    ports:
      - 5432:5432
    volumes:
      - pgisdata:/var/lib/postgis/data/
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DBNAME=docker

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  redisdata:
  pgisdata:
