web:
  restart: always
  build: ./web
  expose:
  - "8000"
  links:
  - postgis:postgis
  volumes:
  - /usr/src/app
  - /usr/src/app/static
  env_file: web/.env.develop
  environment:
    DEBUG: 'true'
  command: /usr/local/bin/gunicorn master_thesis_backend.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
  - "80:80"
  volumes:
    - /www/static
  volumes_from:
  - web
  links:
  - web:web

postgis:
  restart: always
  image: kartoza/postgis:latest
  ports:
  - "5432:5432"
  volumes:
  - pgisdata:/var/lib/postgis/data/

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"
  volumes:
    - redisdata:/data
