# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='chage_status',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
