# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20170223_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='chage_status',
            new_name='charge_status',
        ),
    ]
