# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20170223_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='charge_status',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
