# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20170224_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
    ]
