# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:58
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_tag_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorful.fields.RGBColorField(default='#c96abf'),
        ),
    ]
