# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 10:05
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorful.fields.RGBColorField(default='#2baae9'),
        ),
    ]
