# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 10:14
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations
import tags.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_auto_20170310_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorful.fields.RGBColorField(default=tags.models.get_default_color),
        ),
    ]
