# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
        ('tags', '0013_auto_20170310_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='alarm_config',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alarm.AlarmConfig'),
        ),
    ]
