# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0014_tag_alarm_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='alarm_config',
        ),
    ]
