# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0015_remove_tag_alarm_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.IntegerField(choices=[(0, 'On Alarm'), (0, 'Read Always'), (1, 'Read and handle'), (2, 'Same rights as owner')], default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_users', to='tags.Tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
