# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0016_sharedtag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedtag',
            unique_together=set([('tag', 'user')]),
        ),
    ]
