# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0017_auto_20170425_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedtag',
            name='permissions',
            field=models.IntegerField(choices=[(0, 'On Alarm'), (1, 'Read Always'), (2, 'Read and handle'), (3, 'Same rights as owner')], default=0),
        ),
    ]
