# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0018_auto_20170428_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('view_tag', 'View tag'),)},
        ),
    ]
