# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0019_auto_20170428_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedtag',
            options={'permissions': (('view_shared_tag', 'View shared tag'),)},
        ),
    ]
