# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0021_auto_20170501_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedtag',
            options={'permissions': (('view_sharedtag', 'View shared tag'),)},
        ),
    ]
