# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_auto_20170307_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionmeasurement',
            options={'ordering': ['-time_stamp']},
        ),
    ]
