# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 12:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_auto_20170314_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfigarea',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='alarmconfigarea',
            name='radius',
            field=models.FloatField(default=2, validators=(django.core.validators.MinValueValidator(0),)),
        ),
    ]
