# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_auto_20170314_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='area',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alarm.AlarmConfigArea'),
        ),
        migrations.AddField(
            model_name='alarmconfig',
            name='time_to_deactivate',
            field=models.FloatField(default=60.0),
        ),
    ]
