# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0015_remove_tag_alarm_config'),
        ('alarm', '0004_auto_20170314_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmconfig',
            name='area',
        ),
        migrations.DeleteModel(
            name='AlarmConfig',
        ),
        migrations.DeleteModel(
            name='AlarmConfigArea',
        ),
    ]
