# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 12:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0015_remove_tag_alarm_config'),
        ('alarm', '0005_auto_20170314_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmConfig',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alarm_config', serialize=False, to='tags.Tag')),
                ('time_to_deactivate', models.FloatField(default=60.0)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmConfigArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('radius', models.FloatField(default=2, validators=(django.core.validators.MinValueValidator(0),))),
            ],
        ),
        migrations.AddField(
            model_name='alarmconfig',
            name='area',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alarm.AlarmConfigArea'),
        ),
    ]
