# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 08:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0015_remove_tag_alarm_config'),
        ('alarm', '0006_auto_20170314_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('activate_time', models.DateTimeField()),
                ('state', models.IntegerField(choices=[(0, 'Triggered'), (1, 'Pending'), (2, 'Active'), (3, 'Dismissed')], default=0)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='alarmconfigarea',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
