# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0009_auto_20170315_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='id',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alarm', serialize=False, to='tags.Tag'),
        ),
    ]
