# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:44
from __future__ import unicode_literals

import alarm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0010_auto_20170316_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='random_token',
            field=models.CharField(default=alarm.models.generateRandomToken, max_length=10),
        ),
    ]
