# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:21
from __future__ import unicode_literals

import alarm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0012_auto_20170320_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='random_token',
            field=models.CharField(default=alarm.models.generateRandomToken, max_length=10, unique=True),
        ),
    ]
