# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0013_auto_20170320_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='state',
            field=models.IntegerField(choices=[(0, 'Triggered'), (1, 'Pending'), (2, 'Active'), (3, 'Canceled')], default=0),
        ),
    ]
