# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0014_auto_20170322_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmconfig',
            name='area',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_config', to='alarm.AlarmConfigArea'),
        ),
    ]
