# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userconfiguration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfiguration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL),
        ),
    ]
