# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170209_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfiguration',
            old_name='image',
            new_name='portrait',
        ),
    ]
