# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170209_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfiguration',
            name='portrait',
        ),
        migrations.AddField(
            model_name='userconfiguration',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Portrait'),
        ),
        migrations.AlterField(
            model_name='userconfiguration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conf', to=settings.AUTH_USER_MODEL),
        ),
    ]
