# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170209_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfiguration',
            name='id',
        ),
        migrations.AlterField(
            model_name='userconfiguration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='conf', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
