# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170316_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfiguration',
            old_name='notify_by_amail',
            new_name='notify_by_email',
        ),
    ]
