# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20170316_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfiguration',
            name='notify_by_email',
            field=models.BooleanField(default=False),
        ),
    ]
